# Generated by Django 3.2.20 on 2023-10-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='nicehab',
            field=models.BooleanField(blank=True, null=True, verbose_name='Признак приятной привычки'),
        ),
    ]
