# Generated by Django 3.2.20 on 2023-10-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habits_nicehab'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='periodic',
            field=models.IntegerField(default=0, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
