# Generated by Django 3.2.20 on 2023-10-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20231015_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='periodic',
            field=models.IntegerField(default=1, verbose_name='Периодичность'),
        ),
    ]
