# Generated by Django 3.2.20 on 2023-10-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20231015_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='can_send',
            field=models.BooleanField(default=True),
        ),
    ]
