# Generated by Django 4.2.4 on 2023-10-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habits_can_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='started',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
